version: "3"
services:
  app:
    container_name: jamn_app_1
    build: .
    networks:
      - jamn_net
    ports:
      - 9000:9000
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    command: yarn start:dev
    volumes: 
      - .:/Users/peterwei/workspace/jamn
      - nodemodules:/Users/peterwei/workspace/jamn/node_modules
  redis:
    container_name: jamn_redis_1
    networks:
      - jamn_net
    image: redis
    ports:
      - 6379:6379
  postgres:
    container_name: jamn_postgres_1
    networks:
      - jamn_net
    image: postgis/postgis
    platform: linux/amd64
    restart: always
    env_file:
      - docker.env
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgres
  adminer: # to connect use host.docker.internal
    container_name: jamn_adminer_1
    networks:
      - jamn_net
    image: adminer
    restart: always
    ports:
      - 8080:8080
  graphql_playground:
    container_name: jamn_playground_1
    networks:
      - jamn_net
    image: mkrou/graphql-playground-docker
    restart: always
    env_file:
      - docker.env
    ports: 
      - 8081:8080
volumes:
  nodemodules:
  db:
networks:
  jamn_net: